### ISSUE TITLE
Uncaught typeError : cannot read property 'clientHeight' of null

### ISSUE THREAD

**Issue by Chris88140** [JEALG/Jeedom-hygrometer#3]
Bonjour,

Tout d'abord, merci pour vos widgets.
Par  contre, je rencontre des soucis de rafraîchissement de mes widgets sur mes designs, que ce soit sur tablette (android avec fully kiosk ou sur PC(windows10).
Grâce à la console de Chrome, c'est depuis l'installation du code widget cmd.info.numeric.hygrometer.html.
![image](https://user-images.githubusercontent.com/35608117/126495535-e5788bff-e4b7-4b57-84e2-12074e7c4853.png)
Avez-vous une idée ?, et inutile de vous dire que je suis novice dans la domotique.

Avec cmd.info.numeric.Humidite-Goutte_eau.html et cmd.info.numeric.Température_thermometre.html, ça fonctionne nickel.
Jeedom 4.1.24 et RPI3B+ 

Cordialement,

**Comment by JEALG** [comment]
Bonjour 
Il faudrait passer par le forum se sera plus simple pour suivre et répondre
Car là je n avais pas vu le sujet 
Merci par avance
